name: Pub Release
run-name: Pub Release
on: push

jobs:
  pub-release:
    runs-on: dart-stable
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Authenticate
        run: |
          cd ${{ github.workspace }} \
          && PAT_SECRET_PACKAGE=${{ secrets.PAT_SECRET_PACKAGE }} dart pub token add https://git.mrcyjanek.net/api/packages/mrcyjanek/pub/ --env-var=PAT_SECRET_PACKAGE
      - name: Release
        run: |
          cd ${{ github.workspace }} \
          && make version \
          && PAT_SECRET_PACKAGE=${{ secrets.PAT_SECRET_PACKAGE }} dart pub publish --skip-validation